name: ulam_4_tonyt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_fortune_wheel: ^1.0.0
  rxdart: ^0.27.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  conditional_builder_null_safety: ^0.0.6
  cached_network_image: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png